#!/bin/bash

[[ -z "$1" ]] && echo "The version argument is needed" && exit 1

VER=$1

DIR="ApMon_cpp-"${VER}

echo $DIR

mkdir ${DIR}
cp -r ApMon_cpp.spec AUTHORS BOOTSTRAP ChangeLog configure.ac COPYING INSTALL Makefile.am NEWS README perl src bin examples ${DIR}/


tar czf ${DIR}.tar.gz ${DIR}

rm -rf ${DIR}



